name: update docs

permissions: {}

on:
  workflow_dispatch:

env:
  CLICOLOR_FORCE: "1"

jobs:
  update-put-gif:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - uses: charmbracelet/vhs-action@5bc47255c016b6af28ad6b633ee9a07b79468804 # v1.2.3
        with:
          path: ./tapes/put.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: put-gif
          path: ./docs/put.gif

  update-list-gif:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - uses: charmbracelet/vhs-action@5bc47255c016b6af28ad6b633ee9a07b79468804 # v1.2.3
        with:
          path: ./tapes/list.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: list-gif
          path: ./docs/list.gif

  update-restore-gif:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - uses: charmbracelet/vhs-action@5bc47255c016b6af28ad6b633ee9a07b79468804 # v1.2.3
        with:
          path: ./tapes/restore.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: restore-gif
          path: ./docs/restore.gif

  update-restore-ui-gif:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - uses: charmbracelet/vhs-action@5bc47255c016b6af28ad6b633ee9a07b79468804 # v1.2.3
        with:
          path: ./tapes/restore-ui.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: restore-ui-gif
          path: ./docs/restore-ui.gif

  update-clear-gif:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - uses: charmbracelet/vhs-action@5bc47255c016b6af28ad6b633ee9a07b79468804 # v1.2.3
        with:
          path: ./tapes/clear.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: clear-gif
          path: ./docs/clear.gif

  create-pull-request:
    timeout-minutes: 10
    needs:
      - update-put-gif
      - update-list-gif
      - update-restore-gif
      - update-restore-ui-gif
      - update-clear-gif
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false

      # put
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: put-gif
          path: /tmp/
      - run: cp /tmp/put.gif ./docs/put.gif

      # list
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: list-gif
          path: /tmp/
      - run: cp /tmp/list.gif ./docs/list.gif

      # restore
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: restore-gif
          path: /tmp/
      - run: cp /tmp/restore.gif ./docs/restore.gif

      # restore-ui
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: restore-ui-gif
          path: /tmp/
      - run: cp /tmp/restore-ui.gif ./docs/restore-ui.gif

      # clear
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: clear-gif
          path: /tmp/
      - run: cp /tmp/clear.gif ./docs/clear.gif

      - uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: update docs
          body: ${{ github.sha }}
          branch: docs/update
          branch-suffix: short-commit-hash
