name: update docs

on:
  workflow_dispatch:

env:
  CLICOLOR_FORCE: "1"

jobs:
  update-put-gif:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - name: record put
        uses: charmbracelet/vhs-action@5bc47255c016b6af28ad6b633ee9a07b79468804 # v1.2.3
        with:
          path: ./tapes/put.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: upload put.gif
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: put-gif
          path: ./docs/put.gif

  update-list-gif:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - name: record list
        uses: charmbracelet/vhs-action@5bc47255c016b6af28ad6b633ee9a07b79468804 # v1.2.3
        with:
          path: ./tapes/list.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: upload list.gif
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: list-gif
          path: ./docs/list.gif

  update-restore-gif:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - name: record restore
        uses: charmbracelet/vhs-action@5bc47255c016b6af28ad6b633ee9a07b79468804 # v1.2.3
        with:
          path: ./tapes/restore.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: upload restore.gif
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: restore-gif
          path: ./docs/restore.gif

  update-restore-ui-gif:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - name: record restore-ui
        uses: charmbracelet/vhs-action@5bc47255c016b6af28ad6b633ee9a07b79468804 # v1.2.3
        with:
          path: ./tapes/restore-ui.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: upload restore-ui.gif
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: restore-ui-gif
          path: ./docs/restore-ui.gif

  update-clear-gif:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - name: record clear
        uses: charmbracelet/vhs-action@5bc47255c016b6af28ad6b633ee9a07b79468804 # v1.2.3
        with:
          path: ./tapes/clear.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: upload clear.gif
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: clear-gif
          path: ./docs/clear.gif

  create-pull-request:
    needs:
      - update-put-gif
      - update-list-gif
      - update-restore-gif
      - update-restore-ui-gif
      - update-clear-gif
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      # put
      - name: download put.gif
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: put-gif
          path: /tmp/
      - run: cp /tmp/put.gif ./docs/put.gif

      # list
      - name: download list.gif
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: list-gif
          path: /tmp/
      - run: cp /tmp/list.gif ./docs/list.gif

      # restore
      - name: download restore.gif
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: restore-gif
          path: /tmp/
      - run: cp /tmp/restore.gif ./docs/restore.gif

      # restore-ui
      - name: download restore-ui.gif
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: restore-ui-gif
          path: /tmp/
      - run: cp /tmp/restore-ui.gif ./docs/restore-ui.gif

      # clear
      - name: download clear.gif
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: clear-gif
          path: /tmp/
      - run: cp /tmp/clear.gif ./docs/clear.gif

      - name: create pull request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: update docs
          body: ${{ github.sha }}
          branch: docs/update
          branch-suffix: short-commit-hash
