name: update docs

on:
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: record put
        uses: charmbracelet/vhs-action@v1
        with:
          path: ./docs/tapes/put.tape
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: record list
        uses: charmbracelet/vhs-action@v1
        with:
          path: ./docs/tapes/list.tape
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: record restore
        uses: charmbracelet/vhs-action@v1
        with:
          path: ./docs/tapes/restore.tape
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: record restore-ui
        uses: charmbracelet/vhs-action@v1
        with:
          path: ./docs/tapes/restore-ui.tape
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: record clear
        uses: charmbracelet/vhs-action@v1
        with:
          path: ./docs/tapes/clear.tape
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: update docs
          body: ${{ github.sha }}
          branch: docs/update-
          branch-suffix: short-commit-hash
